apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota
  namespace: dev
spec:
  hard:
    pods: "3"
    requests.cpu: "3"
    requests.memory: 5Gi
    limits.cpu: "10"
    limits.memory: 10Gi